title: Regression with Summary Statistics (RSS)
description: Inferring multiple regression coefficients from univariate regression summary statistics.
theme: jekyll-theme-hacker
show_downloads: true
markdown: kramdown 
